services:

  recruit:
    container_name: recruit_python
    image: recruit
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/srv:cached
    tty: true
    deploy:
      resources:
        limits:
          memory: 512M
